name: Generate snake game

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Update snake animation
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - name: Generate snake animation
        uses: Platane/snk@master
        with:
          github_user_name: Lokendra-Yadav9
          svg_out_path: README.md
          snake_color: 'blue'
          targets: 365

      # Commit and push updated README.md
      - name: Commit files
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git commit -m "Update snake animation"
          git push

