name: Generate snake game

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Update snake animation
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - name: Generate snake animation
        uses: Sutil/snk@master
        with:
          github_user_name: Lokendra-Yadav9
          svg_out_path: dist/github-contribution-grid-snake2.svg
          snake_color: 'blue'

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  
